Controllers/CreateController.cs
/*
 * This Class Controls The Page to Create Networks 
 * Index Method Displays the page that allows you to create networks
 * The add host/switch/network are HTTP POST end points that allow you to send
*data that will be processed and saved to the database
*
*The URLS they handle are noted above each method
*
*/ 




using Microsoft.AspNetCore.Mvc;
using NetworkConfigurator.DataManager;
using NetworkConfigurator.Model;
using Microsoft.AspNetCore.Cors;

// create a save button that passes an instance of a network back to index and save the network to a list of networks in index
namespace NetworkConfigurator.Controllers
{
    //handles all /create urls
    public class CreateController : Controller
    {
        //used for post request to add new components
        public PeopleContext _context;
        public Host newHost;
        public Switch newSwitch;
        public Network newNetwork;
        public CreateDataManager createDM;
       
        static string   NetworkName; 
       
        // Contstruct creates the database context that is used to connect with
        // database to add/ delete update data 
        // also creates an instance of the datamanager and the context is passed to it
        public CreateController(PeopleContext context)
        {
            createDM = new CreateDataManager(context);
            this._context = context;

        }
       
        //  /create or /create/index  returns the view in the views/create folder
        public IActionResult Index()
        {
            return View();
        }



        [HttpPost("Create/AddNetwork")]
        [EnableCors("AllowSpecificOrigin")]
        public IActionResult AddNetwork([FromBody]string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
               
                NetworkName = name; 
                this.newNetwork = new Network();
                this.newNetwork.Name = name;
              
                createDM.SaveNetwork(this.newNetwork);
                
            }

            return RedirectToAction("Index");
        }



        //  /create/addhost 
        // used on post request to add a new host
        [HttpPost("Create/AddNewHost")]
        [EnableCors("AllowSpecificOrigin")]
        public IActionResult AddNewHost([FromBody]PostedHost host)
        {
          
            this.newHost = new Host();
           this.newHost.Name = host.name;
          this.newHost.Adapter = host.eth0;
            newHost.SwitchID = _context.getSwitchID(host.switchName) ;
             this.newHost.NetworkID = _context.getNetworkId(NetworkName);

            CreateDataManager.SaveHost(_context, this.newHost);


            return RedirectToAction("Index");
        }



        // /create/addswitch
        [HttpPost("Create/AddNewSwitch")]
         [EnableCors("AllowSpecificOrigin")]
        public IActionResult AddNewSwitch([FromBody] PostedSwitch switch1)
        {
            this.newSwitch = new Switch();
            this.newSwitch.Name = switch1.name;
            this.newSwitch.Adapter = switch1.eth0;
            this.newSwitch.ports = switch1.ports;
            this.newSwitch.NetworkID = _context.getNetworkId(NetworkName);

            CreateDataManager.SaveSwitch(_context, this.newSwitch); 

            return RedirectToAction("Index");
        }

    }
}

Controllers/HomeController.cs
/*
 * The Class Just Controls the "/" or "" route and only displays the HOme Page
 * 
 * 
 * 
 */



using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NetworkConfigurator.Model;
using NetworkConfigurator.DataManager;

namespace NetworkConfigurator.Controllers
{
    public class HomeController : Controller
    {



        // / or /index
        public IActionResult Index()
        {
            return View("Index");
        }
    }
}

Controllers/SavedController.cs
/*
 * The Class Handles the Saved Page that Displays All the Saved Networks
 * The Detail Method Handles the /Saved/Detail Page that shows Network Details
 * The GetNetwork File Method returns JSON data of the specified network
 
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NetworkConfigurator.DataManager;
using NetworkConfigurator.Model;
using Newtonsoft.Json;
using System.IO; 

namespace NetworkConfigurator.Controllers
{
    public class SavedController : Controller
    {
        PeopleContext context;
        static SavedViewModel network;


       // SavedDataManager savedData;
        //Constructor initiates database context
        public SavedController(PeopleContext _context)
        {
            this.context = _context;
           // savedData = new SavedDataManager(this.context);
        }



        // /saved or /saved/index
        // this method shows the view with the list of all networks that are saved
        public IActionResult Index()
        {
            IList<SavedViewModel> networks = SavedDataManager.GetAllNetworks(context);

            return View(networks);
        }


        // Handles the /Detail/(id) route
        // queries the database for the network with the given id and returns it
        public  IActionResult Detail(int id)
        {
            network  = SavedDataManager.GetNetwork(context, id);

            return View("Detail", network);
        }


        // This method returns network data IN JSON format
        [HttpPost("Saved/GetNetworkFile")]
        public JsonResult GetNetworkFile()
        {
            //string net = JsonConvert.SerializeObject(SavedController.network);
            //return Content(net, "application/json");

            return Json(SavedController.network);
        }



    }
}

Views/Create/Index.cshtml
@{
    ViewData["Title"] = "Network Creator";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

<!-- Maps to /create or /create/index -->
<link rel="stylesheet" href="~/css/createStyles.css" />

<div class="row justify-content-center">
    <div class="col-md-10 col-xs-12">
       <!-- Title Area-->

        <div class="jumbotron ">
            <h2 id="title">Network Builder</h2>
            <div id="newNetwork">
				<label id="newNetworkLabel" for="newNetworkName"> Network Name:  </label>
                <input type="text" id="newNetworkName" />   
            </div>

			<button class="btn btn-primary" id="saveNetwork" onclick="postNewNetwork()"> Save Network </button>
        </div>
		
		<div id="controlButtons" class="">
           <button id="addBtn" class="btn btn-primary" onclick="ToggleVisibility('host')">Add Hosts</button>

           <button id="addSwitchBtn" class="btn btn-primary " onclick="ToggleVisibility('switch')">Add Switch</button>
        </div>

		<div class="row justify-content-center">
       <!-- Display where network is built -->
            <div id="box" class="col-sm-12">


            </div>
        </div>
		
    </div>
</div>

 

        <!-- host dropdown -->

        <div id="addHost">
           <!-- <button id="addHostImageBtn" class="btn btn-primary " onclick="addElement.addHost()"><span class="glyphicon glyphicon-plus-sign"></span> </button> -->
            <br />
            <br />
            <div id="namegroup" class="form-group">
                <label for="name">Name: </label>
                <input id="name" class="form-control" type="text"><br />
            </div>
            <div class="form-group">
                <label for="eth0">eth0: </label>
                <input id="eth0" class="form-control" type="text"><br />
            </div>


            <div class="form-group">
                <label for="switch">Connected Switch: </label>
                <input id="switch" class="form-control" type="text">
            </div>
            <br />

            <button id="saveBtn" onclick="postHost()" class="btn btn-success form-control">Save <span class="glyphicon glyphicon-save"></span></button>
        </div>


        <!-- switch dropdown -->

        <div id="addSwitch">
            <!--<button id="" class="btn btn-primary formBtn" onclick="addElement.addSwitch()"><span class="glyphicon glyphicon-plus-sign"></span> </button> -->
            <br />
            <br />
            <div id="namegroup" class="form-group">
                <label for="switchname"> Switch Name: </label>
                <input id="switchname" class="form-control" type="text"><br />
            </div>
            <div class="form-group">
                <label for="eth0sw">eth0: </label>
                <input id="eth0sw" class="form-control" type="text"><br />
            </div>
            <div class="form-group">
                <label for="eth1">Ports </label>
                <input id="ports" class="form-control" type="text">
            </div>
            <br />

            <button id="saveBtn" onclick="postSwitch()" class="btn btn-success form-control">Save <span class="glyphicon glyphicon-save"></span></button>

        </div>

    


 


<script type="text/javascript" src="~/js/test.js"></script>

Views/Create/OldIndex.cshtml
@{
    ViewData["Title"] = "Network Creator";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}

<!-- Maps to /create or /create/index -->
<link rel="stylesheet" href="~/css/createStyles.css" />

<div class="row justify-content-center">
    <div class="col-md-10 col-xs-12">
       <!-- Title Area-->

        <div class="jumbotron">
            <h2 id="title">Network Builder</h2>
            <div id="newNetwork">
                <input type="text" id="newNetworkName" />
                <button id="saveNetwork" onclick="postNewNetwork()">Save Network </button>
            </div>
            
        </div>
    </div>
</div>

    <div class="row justify-content-center">
        <div class="col-md-10 col-xs-12">

            <!-- Display where network is built -->
            <div id="box">


            </div>

        </div>

        <!-- drop down for hosts-->

    </div>


    <div class="row justify-content-center">
        <a><button id="addBtn" class="btn btn-primary  col-md-4  col-xs-10 col-xs-offset-1" onclick="ToggleVisibility('host')">Add Hosts</button></a>

        <a><button id="addSwitchBtn" class="btn btn-primary col-md-4  col-xs-10 col-xs-offset-1" onclick="ToggleVisibility('switch')">Add Switch</button></a>
    </div>


    <div class="row justify-content-center">


        <!-- host dropdown -->

        <div id="addHost">
            <button id="" class="btn btn-primary " onclick="addElement.addHost()"><span class="glyphicon glyphicon-plus-sign"></span> </button>
            <br />
            <br />
            <div id="namegroup" class="form-group">
                <label for="name">Name: </label>
                <input id="name" class="form-control" type="text"><br />
            </div>
            <div class="form-group">
                <label for="eth0">eth0: </label>
                <input id="eth0" class="form-control" type="text"><br />
            </div>


            <div class="form-group">
                <label for="switch">Connected Switch: </label>
                <input id="switch" class="form-control" type="text">
            </div>
            <br />

            <button id="saveBtn" onclick="postHost()" class="btn btn-success form-control">Save <span class="glyphicon glyphicon-save"></span></button>
        </div>


        <!-- switch dropdown -->

        <div id="addSwitch">
            <button id="" class="btn btn-primary formBtn" onclick="addElement.addSwitch()"><span class="glyphicon glyphicon-plus-sign"></span> </button>
            <br />
            <br />
            <div id="namegroup" class="form-group">
                <label for="switchname"> Switch Name: </label>
                <input id="switchname" class="form-control" type="text"><br />
            </div>
            <div class="form-group">
                <label for="eth0">eth0: </label>
                <input id="eth0" class="form-control" type="text"><br />
            </div>
            <div class="form-group">
                <label for="eth1">Ports </label>
                <input id="ports" class="form-control" type="text">
            </div>
            <br />

            <button id="saveBtn" onclick="postSwitch()" class="btn btn-success form-control">Save <span class="glyphicon glyphicon-save"></span></button>

        </div>

    </div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "V-NetLab";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link rel="stylesheet" href="~/css/HomeIndex.css" />

<div class="container-fluid">
  <div class="row content">
    
    <div class="col-sm-8">

        <div id="mainWell" class="well well-lg">
            <h1>V-NetLab</h1>
            <h3>Network Configuration Tool</h3>
            <img id="netImg" src="~/images/network.png" />
        </div>
    </div>

	<div class="col-sm-4 sidenav">
       <!-- About section goes here -->
        <div class="" id="aboutSection"=>
            <h2 id="aboutTitle"=>About</h2>
			<section>
            <p> The VNetLab Network Configuration Tool Is Used To Add Host and
				Switch Nodes to a Virtual Network. You can configure each Node by
				setting properties on each component. The tool gives you the ability 
				to save your configurations for future viewing. The user may also
				download a configuration file of the network they have created that can
				be used to create networks in network simulating application. 		
						
			</p>
					<br> <br>
			<h3> Team Members </h3>	
			<ul>
                <li>Lead Programmer: Matt Diederick</li>
                <li>Program Leader:  Anthony Figueroa</li>
			    <li>Debugging/HTML: Vincent Hurst</li>
			    <li>Project Assistant: Elmer Fink </li>			
						
			</ul>
			</section>
        </div>     
    </div>	

  </div>
</div>


<!--
<div  class="row">
    <div id="buttons">
       
             <a href="/Create" ><button id="btn1" class="btn btn-primary col-md-4 col-md-offset-3 col-xs-10 col-xs-offset-1" >Add A Network Configuration</button></a>
       
           <a href="/Saved"> <button id=" = btn2" class="btn btn-primary col-md-4 col-xs-10 col-xs-offset-1">View Saved Configurations </button></a>
    </div>
</div>
-->

Views/Saved/Detail.cshtml
@model NetworkConfigurator.Model.SavedViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int id = @Model.Network.ID;
}

<h2>Network Name: @Model.Network.Name</h2> <button class="btn btn-primary" onclick="GetFile()"> Download Configuration File </button>

<table id="hostTable" class="table table-striped table-inverse table-hover table-responsive">
    <caption id="hostsTitle">Hosts</caption>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Adapter</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var host in Model.Hosts)
        {
        <tr>
            <th scope="row">@host.ID</th>
            <td>@host.Name</td>
            <td>@host.Adapter</td>
        </tr>
        }
    </tbody>
</table>

<table id="hostTable" class="table table-striped table-inverse table-hover table-responsive">
    <caption id="hostsTitle">Switchs</caption>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Adapter</th>
            <th>Ports</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var sw in Model.Switchs)
        {
            <tr>
                <th scope="row">@sw.ID</th>
                <td>@sw.Name</td>
                <td>@sw.Adapter</td>
                <td>@sw.ports</td>
               
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript" src="~/js/Detail.js"></script>

Views/Saved/Index.cshtml
@model IList<NetworkConfigurator.Model.SavedViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<link rel="stylesheet" href="~/css/SavedIndex.css" />

<div class="row">
    
        <h2 id="mainTitle">Saved Configurations</h2>


        <ul class="list-group">
            @foreach (var net in Model)
            {
                var hostCount = 0;
                var switchCount = 0;
                <li class="list-group-item d-flex justify-content-between listItem" onmouseover="hover(this)" onmouseout="unhover(this)">
                    
                    <a id="netName" href="/Saved/Detail/@net.Network.ID ">@net.Network.Name </a> 


                    @foreach (var h in net.Hosts)
                    {
                        hostCount++;
                    }
                    @foreach (var s in net.Switchs)
                    {
                        switchCount++;
                    }
                    
                        <span id="hostCount" class="badge  badge-success">Hosts: @hostCount </span>
                        <span id="switchCount" class="badge  badge-success">Switchs: @switchCount </span>

                 
                    

                    @{
                        hostCount = 0;
                        switchCount = 0;
                    }

                </li>

                        }
        </ul>
    </div>


<script type="text/javascript" src="~/js/savedIndex.js"></script>

Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetworkConfigurator</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="style" href="~/css/createStyles.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NetworkConfigurator</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetworkConfigurator</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NetworkConfigurator</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-area="" asp-controller="Create" asp-action="Index">Create Network</a></li>
                            <li><a asp-area="" asp-controller="Saved" asp-action="Index">Saved Networks</a></li>
                        </ul>
                    </div>
                </div>
            </nav>


        </div>
    </div>
    
    <div class="container body-content">
        @RenderBody()
      
    </div>

    <environment names="Development">
			<script src="~/lib/FileSaver.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>